### ISSUE TITLE
Not-an-issue! What's the WebGPU app you're using on tokenhawk.chat?

### ISSUE THREAD

**Issue by qqap** [kayvr/token-hawk#4]
I'm just curious to know the name of the CRT emulator app that you are using on tokenhawk.chat. A couple searches on the internet and I wasn't able to find it. Ty!

**Comment by kayvr** [comment]
It's an emulator I wrote in WebGPU / WebASM. I've been thinking about open sourcing it, but need to find the time.

It's nice to hear there's interest.
